### ISSUE TITLE
grafana-toolkit "command not found" when using "yarn dev"

### ISSUE THREAD

**Issue by nikos** [grafana/simple-app-plugin#6]
To get `"yarn dev"` to work, I added [grafana-toolkit](https://github.com/grafana/grafana/tree/master/packages/grafana-toolkit) (currently under alpha) to the package dependencies with

`yarn add @grafana/toolkit`

After that I was able to successfully compile the typescript code with the commands specified in package.json

**Comment by s-h-a-d-o-w** [comment]
`@grafana/toolkit` has been [added to the dependencies](https://github.com/grafana/simple-app-plugin/blob/master/package.json#L20) a number of months ago, so I suppose it's safe to close this.
